// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// IMPORTANTE: Este arquivo está DEPRECADO. Use @/lib/supabase em vez disso.
// Este arquivo só é mantido para compatibilidade com código antigo.
// O Project ID correto é qgyjfzsihoxtrvrheqvc
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qgyjfzsihoxtrvrheqvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "SUBSTITUA_PELA_CHAVE_ANONIMA_DO_SEU_PROJETO";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});